FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json package-lock.json* ./
RUN npm install

# Disable Next.js telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# Set development environment
ENV NODE_ENV development

# Copy the rest of the application code
COPY . .

# Expose port 3000
EXPOSE 3000

# Start the development server with hot reloading
CMD ["npm", "run", "dev"] 